---
title: "README.md"
---

# Getting and Cleaning Data Course Project

You should create one R script called run_analysis.R that does the following.

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive activity names.
5. Creates a second, independent tidy data set with the average of each variable for each activity and each subject.

# How to use the file

Use the source data links in the Code Book to access and download the source data onto your local folder. You'll have a UCI HAR Dataset folder.
Put run_analysis.R in the parent folder of UCI HAR Dataset, then set it as your working directory using setwd() function in RStudio.
Run source("run_analysis.R"), then it will generate a new file tiny_data.txt in your working directory.

# What you need

The code in run_analysis.R should allow you to run through the steps outlined above and the transformations within those steps. reshape2 and data.table may need to be installed.  That code is in the the .R file.
